### ISSUE TITLE
writings got a redundant part?

### ISSUE THREAD

**Issue by AmeliaTYR** [AY2021S1-CS2113T-W11-4/tp#301]
![image](https://user-images.githubusercontent.com/53657436/98063185-66908700-1e8a-11eb-9374-7e897b0ed396.png)
is the type thing necessary since its just typing in the word type?

ps also if i change my mind i don't wanna write something is there a way out

**Comment by Promethees** [comment]
You need to type in the "type" word to decide the type of the essay (poem/ essay)

**Comment by Promethees** [comment]
I think it's just to help the user get rid of using the tags, which lead to lengthy commands

**Comment by AmeliaTYR** [comment]
but like if there isn't any other accepted input than the word type then no need mebbe?

(also is there a way to cancel writing or does the user have to finish writing to exit this part of the app??)

**Comment by Promethees** [comment]
user needs to type "end" on the new line to indicate the ending of the writing session, I mentioned it in the UG.

**Comment by AmeliaTYR** [comment]
ooo okie as long as the UG explains it
